sudo: required
dist: jammy

language:
    - c
    - c++
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - doxygen
    - clang
    - libstdc++-9-dev
    - libstdc++-10-dev
    - gcc
    - gcc-9
    - gcc-10
    - python3-pip
    - python3-setuptools
    - ninja-build
    - valgrind
install: test/travis-install.sh
script: test/travis-build.sh

