name: 'Build & Test'
on:
  push:
    branches:
      - redfs-main
  pull_request:
    branches:
      - redfs-main

permissions:
  contents: read

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          # 18.04 does not work because of ‘no_sanitize’ attribute
          # cc1: all warnings being treated as errors
          # - ubuntu-18.04
          - ubuntu-latest
    steps:
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        # XXX add in liburing-dev when ubuntu gets updated for github
        run: sudo apt-get update && sudo apt-get install -y clang doxygen gcc gcc-10 gcc-9 valgrind libnuma-dev && sudo wget https://launchpad.net/ubuntu/+archive/primary/+files/liburing2_2.3-3_amd64.deb && sudo wget https://launchpad.net/ubuntu/+archive/primary/+files/liburing-dev_2.3-3_amd64.deb && sudo dpkg -i liburing2_2.3-3_amd64.deb liburing-dev_2.3-3_amd64.deb
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: test/ci-build.sh

